name: sso_invitation-worker

env:
  app: sso_invitation

on:
  push:

jobs:
  build-and-push:
    runs-on: self-hosted
    if: contains('
      refs/heads/develop
      refs/heads/release
      refs/heads/master
      refs/heads/main'
      , github.ref )
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        if: contains('
          refs/heads/release
          refs/heads/master
          refs/heads/main'
          , github.ref)
        with:
          python-version: "3.10"
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v2
        with:
          branch: ${{ github.ref }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          file: Dockerfile
          tags: |
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ github.sha }}
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ env.tag }}
